apiVersion: apps/v1
kind: Deployment
metadata:
  name: weaviate
spec:
  template:
    spec:
      containers:
      - name: weaviate
        volumeMounts:
        - name: dev-weaviate-pvc
          mountPath: /var/lib/weaviate
      volumes:
      - name: dev-weaviate-pvc
        emptyDir: {}
